language: generic

# Use the trusty environment, since the netcdf packages in 12.04 are broken
dist: trusty
sudo: required

before_install:
- export MINICONDA=$HOME/miniconda
- export PATH="$MINICONDA/bin:$PATH"
- hash -r
# Install conda only if necessary
- command -v conda >/dev/null || { wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
   bash miniconda.sh -b -f -p $MINICONDA; }
- conda update --yes conda
- conda remove --yes -n condaenv --all
- conda create --yes -n condaenv python=3.5
- conda install --yes -n condaenv pip
- source activate condaenv
# The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
- sudo rm -rf /dev/shm
- sudo ln -s /run/shm /dev/shm
# These are mostly requirements of instaseis
- conda install --yes -c obspy nomkl obspy netcdf4 psutil python=3.5

- pip install --user cpp-coveralls
- pip install obspy
- sudo apt-get update -qq
- sudo apt-get install -qq gfortran libnetcdff5 libnetcdf-dev libfftw3-dev liblapack-dev libblas-dev openmpi-bin libopenmpi-dev
# Get test wavefields (2GB, takes some time)
- wget https://www.geophysik.uni-muenchen.de/~staehler/kerner_wavefields.tar.bz2
- tar -xvf kerner_wavefields.tar.bz2

install:
- ./copy_templates.sh
- make -j

script:
- make check
- cat tests/mckernel_tests.log
- |
  ./UTILS/make_kerner_input.py
  diff receiver.dat tests/ref_make_input/receiver.dat
  diff CMTSOLUTION tests/ref_make_input/CMTSOLUTION
  diff filters.dat tests/ref_make_input/filters.dat
- ./submit.py -n 2 -q foreground test 

after_success:
- coveralls --gcov-options '\-lp'

cache:
  directories:
    - $HOME/miniconda
