language: generic

# Use the trusty environment, since the netcdf packages in 12.04 are broken
dist: trusty
sudo: required

before_install:
- pip install --user cpp-coveralls
- sudo apt-get update -qq
- sudo apt-get install -qq gfortran libnetcdff5 libnetcdf-dev libfftw3-dev liblapack-dev libblas-dev openmpi-bin libopenmpi-dev
# Get test wavefields (2GB, takes some time)
- wget https://www.geophysik.uni-muenchen.de/~staehler/kerner_wavefields.tar.bz2
- tar -xvf kerner_wavefields.tar.bz2

install:
- ./copy_templates.sh
- make -j

script:
- make check
- cat tests/mckernel_tests.log
- ./UTILS/make_kerner_input.py
- |
  diff receiver.dat tests/ref_make_input/receiver.dat
  diff CMTSOLUTION tests/ref_make_input/CMTSOLUTION
  diff filters.dat tests/ref_make_input/filters.dat

after_success:
- coveralls --gcov-options '\-lp'
